server:
  port: 8090

spring:
  application:
    name: default-service
    
  profiles:
    active: default
    
  cloud:
    stream:
      bindings:
        # Исходящие события
        test-events-out-0:
          destination: test.events
          content-type: application/json
        # Входящие события
        defaultEventsConsumer-in-0:
          destination: default.events
          content-type: application/json
          group: default-group
          
      rabbit:
        bindings:
          test-events-out-0:
            producer:
              routing-key-expression: "'test'"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.defaultservice: INFO
    org.springframework.cloud.stream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [DEFAULT] %logger{36} - %msg%n"