# Глобальная конфигурация для всех микросервисов
# Подключается как spring.config.import=optional:file:../application-global.yml

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    
  cloud:
    stream:
      rabbit:
        binder:
          connection-name-prefix: statarbitrage
        default:
          producer:
            routing-key-expression: headers.routingKey
            confirm-ack-channel: true
          consumer:
            acknowledge-mode: manual
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
            back-off-multiplier: 2.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example: INFO
    org.springframework.cloud.stream: INFO
    org.springframework.amqp: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{service:-UNKNOWN}] %logger{36} - %msg%n"
    
# Общие настройки безопасности    
security:
  require-ssl: false
  
# Таймауты и ресурсы
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  
spring.jpa.properties.hibernate.jdbc.time_zone: UTC