server:
  port: 8081

spring:
  application:
    name: notification-service
    
  profiles:
    active: default
    
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    
  cloud:
    stream:
      bindings:
        # Входящие события уведомлений
        notificationEventsConsumer-in-0:
          destination: notification.events
          content-type: application/json
          group: notification-group
          
      rabbit:
        bindings:
          notificationEventsConsumer-in-0:
            consumer:
              routing-key-expression: "'notification'"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.notification: INFO
    org.springframework.cloud.stream: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [NOTIFICATION] %logger{36} - %msg%n"

# Telegram Bot настройки (заглушка)
telegram:
  bot:
    token: "${TELEGRAM_BOT_TOKEN:YOUR_BOT_TOKEN}"
    username: "${TELEGRAM_BOT_USERNAME:your_bot_username}"