server:
  port: 8086
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: cointegration-service

  profiles:
    active: default

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${DB_URL:jdbc:sqlite:./data/sa-db.sqlite}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        validator.apply_to_ddl: false
        hbm2ddl.auto: none

  #  autoconfigure:
  #    exclude:
  #      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  jackson:
    time-zone: UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: statarbitrage
    password: statarbitrage123

  cloud:
    compatibility-verifier:
      enabled: false
    stream:
      bindings:
        cointegrationEventsConsumer-in-0:
          destination: cointegration.events
          content-type: application/json
          group: cointegration-group
      rabbit:
        bindings:
          cointegrationEventsConsumer-in-0:
            consumer:
              routing-key-expression: "'cointegration'"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.cointegration: INFO

# Настройки коинтеграции
# Cointegration Analysis API
cointegration:
  api:
    url: http://localhost:8000