server:
  port: 8181
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: core-service

  profiles:
    active: default

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${DB_URL:jdbc:sqlite:./data/sa-db.sqlite}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        validator.apply_to_ddl: false
        hbm2ddl.auto: none

  jackson:
    time-zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  rabbitmq:
    host: localhost
    port: 5672
    username: statarbitrage
    password: statarbitrage123

  cloud:
    stream:
      bindings:
        # Исходящие события уведомлений
        notification-events-out-0:
          destination: notification.events
          content-type: application/json
        # Исходящие торговые события
        trading-events-out-0:
          destination: trading.events
          content-type: application/json
        # Исходящие статистические события
        statistics-events-out-0:
          destination: statistics.events
          content-type: application/json
        # Входящие события от OKX
        okx-events-in-0:
          destination: okx.events
          content-type: application/json
          group: core-group
        # Входящие события от Python
        python-events-in-0:
          destination: python.events
          content-type: application/json
          group: core-group

      rabbit:
        bindings:
          notification-events-out-0:
            producer:
              routing-key-expression: "'notification'"
          trading-events-out-0:
            producer:
              routing-key-expression: "'trading'"
          statistics-events-out-0:
            producer:
              routing-key-expression: "'statistics'"

# Vaadin configuration
vaadin:
  productionMode: false
  excludeFromServletContext: true
  launch-browser: true
  urlMapping: /
  allowed-packages: /com/example/statarbitrage/vaadin

# Cointegration Analysis API
cointegration:
  api:
    url: http://localhost:8000

# OKX API Configuration
okx:
  api:
    key: ${OKX_API_KEY:}
    secret: ${OKX_API_SECRET:}
    passphrase: ${OKX_API_PASSPHRASE:}
    sandbox: ${OKX_API_SANDBOX:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.core: INFO