server:
  port: 8181
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: core-service

  profiles:
    active: default

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/statarbitrage}
    username: ${DB_USERNAME:statuser}
    password: ${DB_PASSWORD:statpass123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        validator.apply_to_ddl: false
        hbm2ddl.auto: none
        format_sql: true
    show-sql: false

  jackson:
    time-zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}

  cloud:
    compatibility-verifier:
      enabled: false
    stream:
      bindings:
        notification-events-out-0:
          destination: notification.events
          content-type: application/json
          group: notification-group
        csv-events-out-0:
          destination: csv.events
          content-type: application/json
          group: csv-group
        cointegrationEventsConsumer-in-0:
          destination: cointegration.events
          content-type: application/json
          group: cointegration-group
      rabbit:
        bindings:
          notification-events-out-0:
            producer:
              routing-key-expression: "'notification'"
          csv-events-out-0:
            producer:
              routing-key-expression: "'csv'"
          cointegrationEventsConsumer-in-0:
            consumer:
              routing-key-expression: "'cointegration'"

# Vaadin configuration
vaadin:
  productionMode: false
  excludeFromServletContext: true
  launch-browser: true
  urlMapping: /
  allowed-packages: /com/example/statarbitrage/vaadin

# Cointegration Analysis API
cointegration:
  api:
    url: http://localhost:8000

# OKX API Configuration
okx:
  api:
    key: ${OKX_API_KEY:}
    secret: ${OKX_API_SECRET:}
    passphrase: ${OKX_API_PASSPHRASE:}
    sandbox: ${OKX_API_SANDBOX:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.core: INFO