server:
  port: 8181
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: core-service

  profiles:
    active: default

  main:
    allow-circular-references: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/statarbitrage}
    username: ${DB_USERNAME:statuser}
    password: ${DB_PASSWORD:statpass123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        validator.apply_to_ddl: false
        hbm2ddl.auto: none
        format_sql: true
    show-sql: false

  jackson:
    time-zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-on-migrate: true
    validate-on-migrate: false
    out-of-order: false
  #    repair: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      client:
        config:
          candles-service:
            connectTimeout: 30000  # 30 секунд
            readTimeout: 43200000    # 12 ч
          default:
            connectTimeout: 10000  # 10 секунд для остальных
            readTimeout: 60000     # 1 минута для остальных
    stream:
      bindings:
        core-events-out-0:
          destination: core.events
          content-type: application/json
        cointegrationEventsConsumer-in-0:
          destination: cointegration.events
          content-type: application/json
          group: core-group # создаст очередь cointegration.events.core-group и тоже будет получать свои копии сообщений
      rabbit:
        bindings:
          core-events-out-0:
            producer:
              routing-key-expression: "'core'"
          cointegrationEventsConsumer-in-0:
            consumer:
              routing-key-expression: "'cointegration'"

# Vaadin configuration
vaadin:
  productionMode: false
  excludeFromServletContext: true
  launch-browser: true
  urlMapping: /
  allowed-packages: /com/example/statarbitrage/vaadin
  devmode:
    allowlist: "localhost,127.0.0.1"

# Cointegration Analysis API
cointegration:
  api:
    url: http://localhost:8000

# OKX API Configuration
okx:
  api:
    key: ${OKX_API_KEY:}
    secret: ${OKX_API_SECRET:}
    passphrase: ${OKX_API_PASSPHRASE:}
    sandbox: ${OKX_API_SANDBOX:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.core: INFO
    com.vaadin.flow.spring.SpringInstantiator: WARN
    org.hibernate.AssertionFailure: WARN  # Уменьшаем спам от Hibernate
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN  # Уменьшаем спам от SQL ошибок дубликатов
    root: INFO
  file:
    name: core/logs/core.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      clean-history-on-start: true
  pattern:
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p ${PID:-?} --- [%15.15t] %-40.40logger{39} : %m%n"