server:
  port: 8088
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: okx-service

  profiles:
    active: default

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  jackson:
    time-zone: UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: statarbitrage
    password: statarbitrage123

  cloud:
    compatibility-verifier:
      enabled: false
    stream:
      bindings:
        okxEventsConsumer-in-0:
          destination: okx.events
          content-type: application/json
          group: okx-group
      rabbit:
        bindings:
          okxEventsConsumer-in-0:
            consumer:
              routing-key-expression: "'okx'"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.okx: INFO