server:
  port: 8087

spring:
  application:
    name: 3commas-service
    
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.commas: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [3COMMAS] %logger{36} - %msg%n"