server:
  port: 8083
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: csv-service

  profiles:
    active: default

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  jackson:
    time-zone: UTC

  rabbitmq:
    host: localhost
    port: 5672
    username: statarbitrage
    password: statarbitrage123

  cloud:
    stream:
      bindings:
        csvEventsConsumer-in-0:
          destination: csv.events
          content-type: application/json
          group: csv-group
      rabbit:
        bindings:
          csvEventsConsumer-in-0:
            consumer:
              routing-key-expression: "'csv'"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.csv: INFO