-- Initial schema based on JPA entities with proper AUTOINCREMENT IDs

-- Settings table
CREATE TABLE settings
(
    id                                     INTEGER PRIMARY KEY AUTOINCREMENT,
    timeframe                              TEXT,
    candle_limit                           REAL,
    min_z                                  REAL,
    min_window_size                        REAL,
    max_p_value                            REAL,
    max_adf_value                          REAL,
    min_r_squared                          REAL,
    min_correlation                        REAL,
    min_volume                             REAL,
    check_interval                         REAL,
    max_long_margin_size                   REAL,
    max_short_margin_size                  REAL,
    leverage                               REAL,
    exit_take                              REAL,
    exit_stop                              REAL,
    exit_z_min                             REAL,
    exit_z_max                             REAL,
    exit_z_max_percent                     REAL,
    exit_time_minutes                      REAL,
    exit_break_even_percent                REAL,
    exit_negative_z_min_profit_percent     REAL,
    use_pairs                              REAL,
    auto_trading_enabled                   BOOLEAN DEFAULT FALSE,
    use_min_z_filter                       BOOLEAN DEFAULT TRUE,
    use_min_r_squared_filter               BOOLEAN DEFAULT TRUE,
    use_max_p_value_filter                 BOOLEAN DEFAULT TRUE,
    use_max_adf_value_filter               BOOLEAN DEFAULT TRUE,
    use_min_correlation_filter             BOOLEAN DEFAULT TRUE,
    use_min_volume_filter                  BOOLEAN DEFAULT TRUE,
    use_exit_take                          BOOLEAN DEFAULT TRUE,
    use_exit_stop                          BOOLEAN DEFAULT TRUE,
    use_exit_z_min                         BOOLEAN DEFAULT TRUE,
    use_exit_z_max                         BOOLEAN DEFAULT TRUE,
    use_exit_z_max_percent                 BOOLEAN DEFAULT TRUE,
    use_exit_time_minutes                  BOOLEAN DEFAULT TRUE,
    use_exit_break_even_percent            BOOLEAN DEFAULT TRUE,
    use_exit_negative_z_min_profit_percent BOOLEAN DEFAULT TRUE,
    use_cointegration_stability_filter     BOOLEAN DEFAULT TRUE,
    minimum_lot_blacklist                  TEXT    DEFAULT 'ETH-USDT-SWAP,BTC-USDT-SWAP',
    observed_pairs                         TEXT    DEFAULT '',
    use_z_score_scoring                    BOOLEAN DEFAULT TRUE,
    use_pixel_spread_scoring               BOOLEAN DEFAULT TRUE,
    use_cointegration_scoring              BOOLEAN DEFAULT TRUE,
    use_model_quality_scoring              BOOLEAN DEFAULT TRUE,
    use_statistics_scoring                 BOOLEAN DEFAULT TRUE,
    use_bonus_scoring                      BOOLEAN DEFAULT TRUE,
    z_score_scoring_weight                 REAL    DEFAULT 40.0,
    pixel_spread_scoring_weight            REAL    DEFAULT 25.0,
    cointegration_scoring_weight           REAL    DEFAULT 25.0,
    model_quality_scoring_weight           REAL    DEFAULT 20.0,
    statistics_scoring_weight              REAL    DEFAULT 10.0,
    bonus_scoring_weight                   REAL    DEFAULT 5.0
);

-- ChartSettings table
CREATE TABLE chart_settings
(
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    chart_type          TEXT UNIQUE NOT NULL,
    show_z_score        BOOLEAN DEFAULT TRUE,
    show_combined_price BOOLEAN DEFAULT TRUE,
    show_pixel_spread   BOOLEAN DEFAULT FALSE,
    show_ema            BOOLEAN DEFAULT FALSE,
    show_stoch_rsi      BOOLEAN DEFAULT FALSE,
    show_profit         BOOLEAN DEFAULT FALSE,
    show_entry_point    BOOLEAN DEFAULT TRUE
);

-- TradeHistory table
CREATE TABLE trade_history
(
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    long_ticker            TEXT,
    short_ticker           TEXT,
    pair_uuid              TEXT,
    min_profit_minutes     TEXT,
    max_profit_minutes     TEXT,
    min_profit_percent     DECIMAL,
    max_profit_percent     DECIMAL,
    current_profit_usdt    DECIMAL,
    current_profit_percent DECIMAL,
    min_long_percent       DECIMAL,
    max_long_percent       DECIMAL,
    current_long_percent   DECIMAL,
    min_short_percent      DECIMAL,
    max_short_percent      DECIMAL,
    current_short_percent  DECIMAL,
    min_z                  DECIMAL,
    max_z                  DECIMAL,
    current_z              REAL,
    min_corr               DECIMAL,
    max_corr               DECIMAL,
    current_corr           REAL,
    exit_take              REAL,
    exit_stop              REAL,
    exit_z_min             REAL,
    exit_z_max             REAL,
    exit_time_minutes      REAL,
    exit_reason            TEXT,
    entry_time             TEXT,
    timestamp              TEXT
);

-- PairData table - based on entity with all @Column annotations
CREATE TABLE pair_data
(
    id                                              INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid                                            TEXT NOT NULL UNIQUE,
    version                                         BIGINT,
    status                                          TEXT,
    error_description                               TEXT,
    pair_name                                       TEXT,
    long_ticker                                     TEXT,
    short_ticker                                    TEXT,
    long_ticker_entry_price                         REAL,
    long_ticker_current_price                       REAL,
    short_ticker_entry_price                        REAL,
    short_ticker_current_price                      REAL,
    mean_entry                                      REAL,
    mean_current                                    REAL,
    spread_entry                                    REAL,
    spread_current                                  REAL,
    z_score_entry                                   REAL,
    z_score_current                                 REAL,
    p_value_entry                                   REAL,
    p_value_current                                 REAL,
    adf_pvalue_entry                                REAL,
    adf_pvalue_current                              REAL,
    correlation_entry                               REAL,
    correlation_current                             REAL,
    alpha_entry                                     REAL,
    alpha_current                                   REAL,
    beta_entry                                      REAL,
    beta_current                                    REAL,
    std_entry                                       REAL,
    std_current                                     REAL,
    z_score_changes                                 DECIMAL,
    long_usdt_changes                               DECIMAL,
    long_percent_changes                            DECIMAL,
    short_usdt_changes                              DECIMAL,
    short_percent_changes                           DECIMAL,
    portfolio_before_trade_usdt                     DECIMAL,
    profit_usdt_changes                             DECIMAL,
    portfolio_after_trade_usdt                      DECIMAL,
    profit_percent_changes                          DECIMAL,
    minutes_to_min_profit_percent                   BIGINT,
    minutes_to_max_profit_percent                   BIGINT,
    min_profit_percent_changes                      DECIMAL,
    max_profit_percent_changes                      DECIMAL,
    formatted_time_to_min_profit                    TEXT,
    formatted_time_to_max_profit                    TEXT,
    formatted_profit_long                           TEXT,
    formatted_profit_short                          TEXT,
    formatted_profit_common                         TEXT,
    timestamp                                       BIGINT,
    entry_time                                      BIGINT,
    updated_time                                    BIGINT,
    max_z                                           DECIMAL,
    min_z                                           DECIMAL,
    max_long                                        DECIMAL,
    min_long                                        DECIMAL,
    max_short                                       DECIMAL,
    min_short                                       DECIMAL,
    max_corr                                        DECIMAL,
    min_corr                                        DECIMAL,
    exit_reason                                     TEXT,
    close_at_breakeven                              BOOLEAN DEFAULT FALSE,
    long_ticker_candles_json                        TEXT,
    short_ticker_candles_json                       TEXT,
    z_score_history_json                            TEXT,
    profit_history_json                             TEXT,
    pixel_spread_history_json                       TEXT,
    settings_timeframe                              TEXT,
    settings_candle_limit                           REAL,
    settings_min_z                                  REAL,
    settings_min_window_size                        REAL,
    settings_min_p_value                            REAL,
    settings_max_adf_value                          REAL,
    settings_min_r_squared                          REAL,
    settings_min_correlation                        REAL,
    settings_min_volume                             REAL,
    settings_check_interval                         REAL,
    settings_max_long_margin_size                   REAL,
    settings_max_short_margin_size                  REAL,
    settings_leverage                               REAL,
    settings_exit_take                              REAL,
    settings_exit_stop                              REAL,
    settings_exit_z_min                             REAL,
    settings_exit_z_max                             REAL,
    settings_exit_z_max_percent                     REAL,
    settings_exit_time_minutes                      REAL,
    settings_exit_breakeven_percent                 REAL,
    settings_use_pairs                              REAL,
    settings_auto_trading_enabled                   BOOLEAN,
    settings_use_min_z_filter                       BOOLEAN,
    settings_use_min_r_squared_filter               BOOLEAN,
    settings_use_min_p_value_filter                 BOOLEAN,
    settings_use_max_adf_value_filter               BOOLEAN,
    settings_use_min_correlation_filter             BOOLEAN,
    settings_use_min_volume_filter                  BOOLEAN,
    settings_use_exit_take                          BOOLEAN,
    settings_use_exit_stop                          BOOLEAN,
    settings_use_exit_z_min                         BOOLEAN,
    settings_use_exit_z_max                         BOOLEAN,
    settings_use_exit_z_max_percent                 BOOLEAN,
    settings_use_exit_time_hours                    BOOLEAN,
    settings_use_exit_break_even_percent            BOOLEAN,
    settings_minimum_lot_blacklist                  TEXT,
    use_z_score_scoring                             BOOLEAN,
    z_score_scoring_weight                          REAL,
    use_pixel_spread_scoring                        BOOLEAN,
    pixel_spread_scoring_weight                     REAL,
    use_cointegration_scoring                       BOOLEAN,
    cointegration_scoring_weight                    REAL,
    use_model_quality_scoring                       BOOLEAN,
    model_quality_scoring_weight                    REAL,
    use_statistics_scoring                          BOOLEAN,
    statistics_scoring_weight                       REAL,
    use_bonus_scoring                               BOOLEAN,
    bonus_scoring_weight                            REAL,
    settings_use_exit_negative_z_min_profit_percent BOOLEAN,
    settings_exit_negative_z_min_profit_percent     REAL
);

-- Position table
CREATE TABLE positions
(
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    position_id            TEXT UNIQUE,
    pair_data_id           BIGINT,
    symbol                 TEXT,
    type                   TEXT,
    size                   DECIMAL(19, 8),
    entry_price            DECIMAL(19, 8),
    closing_price          DECIMAL(19, 8),
    current_price          DECIMAL(19, 8),
    leverage               DECIMAL(19, 8),
    allocated_amount       DECIMAL(19, 8),
    unrealized_pnl_usdt    DECIMAL(19, 8),
    unrealized_pnl_percent DECIMAL(19, 8),
    realized_pnl_usdt      DECIMAL(19, 8),
    realized_pnl_percent   DECIMAL(19, 8),
    opening_fees           DECIMAL(19, 8),
    funding_fees           DECIMAL(19, 8),
    closing_fees           DECIMAL(19, 8),
    status                 TEXT,
    open_time              TIMESTAMP,
    last_updated           TIMESTAMP,
    metadata               TEXT,
    external_order_id      TEXT
);

-- Create indexes for better performance
CREATE INDEX idx_pairdata_uuid ON pair_data (uuid);
CREATE INDEX idx_pairdata_status ON pair_data (status);
CREATE INDEX idx_chart_settings_type ON chart_settings (chart_type);
CREATE INDEX idx_trade_history_uuid ON trade_history (pair_uuid);
CREATE INDEX idx_positions_status ON positions (status);
CREATE INDEX idx_positions_pair_data_id ON positions (pair_data_id);